version: '3.3'

services:
  comments_aio_pg_12:
    restart: always
    image: postgres:12.17
    container_name: comments_aio_pg_12
    ports:
      - 5435:5432
    environment:
      - TZ=Asia/Bishkek
      - PGTZ=Asia/Bishkek
      - POSTGRES_DB=comments_aio_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      comments_aio_network:
    volumes:
      - comments_aio_pg_data:/var/lib/postgresql/data

  comments_aio_redis:
    container_name: comments_aio_redis
    restart: always
    image: redis:5-alpine

    environment:
      - TZ=Asia/Bishkek
    volumes:
      - comments_aio_redis_data:/data
    ports:
      - 6379:6379
    networks:
      comments_aio_network:


networks:
  comments_aio_network:
volumes:
  comments_aio_redis_data:
  comments_aio_pg_data: