"""news_categories

Revision ID: 4bda85823d17
Revises: 74ac893b39c6
Create Date: 2024-09-22 17:06:54.742920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bda85823d17'
down_revision: Union[str, None] = '74ac893b39c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('category', sa.Enum('WORLD_EVENTS', 'POLITICS', 'ECONOMY', 'SCIENCE_AND_TECHNOLOGY', 'HEALTHCARE', 'ENVIRONMENT', 'CULTURE_AND_ARTS', 'SPORTS', 'SOCIETY', 'ENTERTAINMENT', name='newstypeenum'), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'news_id')
    )
    op.create_table('users_categories_subscriptions',
    sa.Column('category', sa.Enum('WORLD_EVENTS', 'POLITICS', 'ECONOMY', 'SCIENCE_AND_TECHNOLOGY', 'HEALTHCARE', 'ENVIRONMENT', 'CULTURE_AND_ARTS', 'SPORTS', 'SOCIETY', 'ENTERTAINMENT', name='newstypeenum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_categories_subscriptions')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
